### ISSUE TITLE
What does the Unyson extension Social do?

### ISSUE THREAD

**Issue by charlesjohn2004** [ThemeFuse/Unyson-Social-Extension#2]
Hi,
I would like to know what the purpose of the extension 'Social' Does it post to facebook and twitter using the contents of the site where it is installed? or does it do something else. I followed its documentation and also tried to find some videos, but none actually explains its working.

Thanks,
Charles

**Comment by ghost** [comment]
The Social extension is very small, all it does is: Provide options for the user to enter his social profile details in extension settings page, and provide the theme developer functions to use the data entered by the user.
